import = ["/home/akib/.config/alacritty/themes/gruvbox_material.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[window]
opacity = 1

[cursor]
style = "Beam"
vi_mode_style = "Block"

[env]
TERM = "alacritty"

[font]
size = 11.0

[scrolling]
history = 10000

[window.padding]
x = 16
y = 16

