# .sops.yaml

keys:
  - &primary age1y7cx0nfpyh6jpn85wms4gckldpncf4vg50n3d6ksframphtlysgqg2a73a
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
