name: 'Flake Check'

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up Git credentials
        run: |
          git config --global url."https://${{ secrets.GITLAB_ACCESS_TOKEN }}:x-oauth-basic@gitlab.com".insteadOf "https://gitlab.com"

      - name: Run flake checks for all configured flake inputs
        run: |
          nix flake check \
            --override-input mySsecrets "git+https://gitlab.com/myname/secrects.git?ref=main&shallow=1" \
            --override-input my-devShells path:./devshells \
            --override-input nixvim path:./pkgs/nixvim \
            --no-update-lock-file --no-write-lock-file --accept-flake-config
