name: 'Flake Check'

on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check --override-input my-devShells path:./devshells --override-input nixvim path:./pkgs/nixVim --no-update-lock-file --no-write-lock-file --accept-flake-config
