name: Nix build

# which events should trigger this workflow
on:
  push:
    # trigger workflow on push request to main & dev branch
    branches:
      - main
      - dev

# jobs to run
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

      - name: build system test for desktop
        run: nixos-test -I nixpkgs=channel:nixos-23.11 -I nixos-config=tests/desktop.nix
